services:
  - type: web
    name: foodbank-sms-service
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn foodbank_app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: FLASK_ENV
        value: production
